"""add status and last_contacted_at to customers

Revision ID: 745bb2d486ee
Revises: a07fce9fbd5c
Create Date: 2026-05-28 23:42:00.478914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '745bb2d486ee'
down_revision: Union[str, Sequence[str], None] = 'a07fce9fbd5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('status', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('last_contacted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_customers_last_contacted_at'), 'customers', ['last_contacted_at'], unique=False)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_last_contacted_at'), table_name='customers')
    op.drop_column('customers', 'last_contacted_at')
    op.drop_column('customers', 'status')
    # ### end Alembic commands ###
