"""add salon fields to customers

Revision ID: 7bbc58345bd3
Revises: 745bb2d486ee
Create Date: 2026-06-01 02:02:20.579947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bbc58345bd3'
down_revision: Union[str, Sequence[str], None] = '745bb2d486ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_customers_last_visit_date'), 'customers', ['last_visit_date'], unique=False)
    op.create_index(op.f('ix_customers_next_appointment_date'), 'customers', ['next_appointment_date'], unique=False)
    op.create_index(op.f('ix_customers_service_type'), 'customers', ['service_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_service_type'), table_name='customers')
    op.drop_index(op.f('ix_customers_next_appointment_date'), table_name='customers')
    op.drop_index(op.f('ix_customers_last_visit_date'), table_name='customers')
    op.drop_column('customers', 'service_type')
    op.drop_column('customers', 'next_appointment_date')
    op.drop_column('customers', 'last_visit_date')
    # ### end Alembic commands ###
